"use client";

import Image from "next/image";
import { useEffect, useRef, type CSSProperties, type RefObject } from "react";
import type { LetterContent } from "@/data/site-content";
import { BRAND_GEOMETRY } from "@/lib/brand-geometry";
import { gsap, registerGsap, pickVideoSource, prefersReducedMotion } from "@/lib/animation";

type Mode = "sequence" | "solid" | "posters";

interface VideoLettermarkProps {
  letters: readonly LetterContent[];
  /**
   * "sequence": floral wordmark over the video letters, both exposed through refs for the scroll timeline.
   * "solid": floral wordmark only (hero in the reduced-motion fallback).
   * "posters": video letters visible with poster images and no video elements.
   */
  mode?: Mode;
  /** In "sequence" mode, starts/pauses the letter videos. */
  playing?: boolean;
  solidRef?: RefObject<HTMLDivElement | null>;
  videoLayerRef?: RefObject<HTMLDivElement | null>;
}

const pct = (fraction: number) => `${fraction * 100}%`;

const mask = (url: string): CSSProperties => ({
  maskImage: `url(${url})`,
  WebkitMaskImage: `url(${url})`,
  maskSize: "100% 100%",
  WebkitMaskSize: "100% 100%",
  maskRepeat: "no-repeat",
  WebkitMaskRepeat: "no-repeat",
});

/**
 * KIKI built from the brand's own letterforms.
 *
 * The element is the "letter box": the ink bounds of the four letters in the
 * supplied wordmark. Each letter is a slot-sized element masked by that
 * letter's alpha (public/brand/mask-*.png, generated by scripts/brand-geometry.mjs)
 * holding its poster and video. A white layer masked by a dilated copy of the
 * same letter sits beneath it and reads as the crisp outline. The floral
 * wordmark PNG is positioned so its letters coincide exactly with the box, so
 * the scroll timeline can crossfade one into the other.
 */
export default function VideoLettermark({
  letters,
  mode = "sequence",
  playing = false,
  solidRef,
  videoLayerRef,
}: VideoLettermarkProps) {
  const g = BRAND_GEOMETRY;
  const rootRef = useRef<HTMLDivElement>(null);
  const videoRefs = useRef<Array<HTMLVideoElement | null>>([]);
  const visibleRef = useRef(true);

  /* Pause videos while the wordmark is off screen. */
  useEffect(() => {
    const root = rootRef.current;
    if (!root || mode !== "sequence") return;
    const io = new IntersectionObserver(
      ([entry]) => {
        visibleRef.current = entry.isIntersecting;
        videoRefs.current.forEach((v) => {
          if (!v || !v.dataset.loaded) return;
          if (entry.isIntersecting && playing) v.play().catch(() => {});
          else v.pause();
        });
      },
      { threshold: 0 },
    );
    io.observe(root);
    return () => io.disconnect();
  }, [mode, playing]);

  /* Start / stop playback. Sources are attached lazily on first play. */
  useEffect(() => {
    if (mode !== "sequence") return;
    videoRefs.current.forEach((v, i) => {
      if (!v) return;
      if (playing && visibleRef.current) {
        if (!v.dataset.loaded) {
          const src = pickVideoSource(letters[i].video);
          if (!src) return;
          v.dataset.loaded = "1";
          v.src = src;
          v.load();
        }
        v.play().catch(() => {});
      } else {
        v.pause();
      }
    });
  }, [playing, mode, letters]);

  /* Fade each video in once it is actually rendering frames, and drift it inside its mask. */
  useEffect(() => {
    if (mode !== "sequence" || prefersReducedMotion()) return;
    registerGsap();
    const listeners: Array<() => void> = [];
    const ctx = gsap.context(() => {
      videoRefs.current.forEach((v, i) => {
        if (!v) return;
        const onPlaying = () => gsap.to(v, { opacity: 1, duration: 0.9, ease: "power2.out" });
        const onError = () => gsap.set(v, { opacity: 0 });
        v.addEventListener("playing", onPlaying);
        v.addEventListener("error", onError);
        listeners.push(() => {
          v.removeEventListener("playing", onPlaying);
          v.removeEventListener("error", onError);
        });
        gsap.to(v, {
          xPercent: i % 2 ? 1.6 : -1.6,
          yPercent: i % 2 ? -1.3 : 1.4,
          duration: 9 + i * 2.5,
          ease: "sine.inOut",
          yoyo: true,
          repeat: -1,
        });
      });
    }, rootRef);
    return () => {
      listeners.forEach((off) => off());
      ctx.revert();
    };
  }, [mode]);

  const showSolid = mode === "sequence" || mode === "solid";
  const showVideoLayer = mode === "sequence" || mode === "posters";
  const pad = g.outlinePad;
  const floral = g.floral.letter;

  return (
    <div ref={rootRef} className="relative w-full" style={{ aspectRatio: `1 / ${g.letterAspect}` }}>
      {showVideoLayer && (
        <div
          ref={videoLayerRef}
          className="absolute inset-0 will-change-transform"
          style={{ opacity: mode === "posters" ? 1 : 0 }}
          aria-hidden={mode === "sequence"}
          role={mode === "posters" ? "img" : undefined}
          aria-label={mode === "posters" ? "KIKI" : undefined}
        >
          {/* White outlines: dilated letter masks beneath the letters. */}
          {g.slots.map((s) => (
            <div
              key={`outline-${s.id}`}
              className="absolute bg-white"
              style={{
                left: pct(s.x - pad.x),
                width: pct(s.w + 2 * pad.x),
                top: pct(-pad.y),
                height: pct(1 + 2 * pad.y),
                ...mask(`/brand/outline-${s.id}.png`),
              }}
            />
          ))}

          {/* The letters themselves, each masked to its own glyph. */}
          {letters.map((l, i) => {
            const s = g.slots[i];
            return (
              <div
                key={l.id}
                className="absolute top-0 h-full overflow-hidden"
                style={{ left: pct(s.x), width: pct(s.w), ...mask(`/brand/mask-${s.id}.png`) }}
              >
                <Image
                  src={l.video.poster}
                  alt=""
                  fill
                  sizes="(max-width: 767px) 48vw, 36vw"
                  quality={82}
                  className="object-cover"
                  style={{ transform: "scale(1.06)", objectPosition: l.focus }}
                />
                {mode === "sequence" && (
                  <video
                    ref={(el) => {
                      videoRefs.current[i] = el;
                    }}
                    muted
                    loop
                    playsInline
                    preload="metadata"
                    poster={l.video.poster}
                    aria-label={l.label}
                    tabIndex={-1}
                    className="absolute inset-0 h-full w-full object-cover"
                    style={{ transform: "scale(1.08)", opacity: 0, objectPosition: l.focus }}
                  />
                )}
              </div>
            );
          })}
        </div>
      )}

      {showSolid && (
        <div
          ref={solidRef}
          className="absolute"
          role="img"
          aria-label="KIKI on the Miami River"
          style={{
            left: pct(-floral.x / floral.w),
            top: pct(-floral.y / floral.h),
            width: pct(1 / floral.w),
            height: pct(1 / floral.h),
            filter: "drop-shadow(0 6px 26px rgba(14, 44, 147, 0.28))",
          }}
        >
          <Image
            src={g.floral.src}
            alt=""
            fill
            priority
            sizes="(max-width: 767px) 110vw, 60vw"
            className="object-contain"
          />
        </div>
      )}
    </div>
  );
}
