/**
 * GENERATED by scripts/brand-geometry.mjs from the supplied wordmark PNGs. Do not edit by hand.
 * All values are fractions of the KIKI letter box (the four letters' ink bounds in the plain wordmark).
 */
export const BRAND_GEOMETRY = {
  /** Letter box aspect: height / width. */
  letterAspect: 0.29461,
  /** Per-letter slots inside the letter box. */
  slots: [{"id":"k1","x":0,"w":0.3107067879636109},{"id":"i1","x":0.34009797060881736,"w":0.14065780265920225},{"id":"k2","x":0.509447165850245,"w":0.31490552834149754},{"id":"i2","x":0.8551434569629112,"w":0.14485654303708886}],
  /** Dilation padding of the outline masks, as a fraction of the letter box width/height. */
  outlinePad: { x: 0.00980, y: 0.03325 },
  /** Plain wordmark (with "On the Miami River"): where the letter box sits inside the full image. */
  wordmark: { src: "/brand/kiki-wordmark.png", width: 2169, height: 725, letter: { x: 0.16229, y: 0.14621, w: 0.65883, h: 0.58069 }, subtitleBottom: 0.2637 },
  /** Floral wordmark and its flowers-only derivative: where the letter box sits inside the full image. */
  floral: { src: "/brand/kiki-wordmark-flowers.png", flowersSrc: "/brand/kiki-flowers-only.png", width: 2017, height: 780, letter: { x: 0.12524, y: 0.21667, w: 0.73126, h: 0.55710 } },
} as const;
