/**
 * GENERATED by scripts/brand-geometry.mjs from the traced KIKI logo. Do not edit by hand.
 * All values are fractions of the KIKI letter box (the four letters' ink bounds).
 */
export const BRAND_GEOMETRY = {
  /** Letter box aspect: height / width. */
  letterAspect: 0.27417,
  /** Per-letter slots inside the letter box. */
  slots: [{"id":"k1","x":0,"w":0.30833333333333335},{"id":"i1","x":0.3416666666666667,"w":0.14041666666666666},{"id":"k2","x":0.51875,"w":0.30791666666666667},{"id":"i2","x":0.8595833333333334,"w":0.14041666666666666}],
  /** Dilation padding of the outline masks, as a fraction of the letter box width/height. */
  outlinePad: { x: 0.00667, y: 0.02432 },
  /** The logo image, and where the letter box sits inside it. */
  wordmark: { src: "/brand/kiki-wordmark.png", svg: "/brand/kiki-logo.svg", width: 2400, height: 658, letter: { x: 0.00000, y: 0.00000, w: 1.00000, h: 1.00000 } },
} as const;
