/** GENERATED by scripts/extract-petals.mjs from the floral wordmark. Do not edit by hand. */
export type SpriteKind = "bract" | "bud" | "leaf";
export interface PetalSprite { kind: SpriteKind; src: string; w: number; h: number }
export const PETAL_SPRITES: readonly PetalSprite[] = [
  {
    "kind": "bract",
    "src": "/petals/petal-01-soft.png",
    "w": 78,
    "h": 61
  },
  {
    "kind": "bract",
    "src": "/petals/petal-02-soft.png",
    "w": 71,
    "h": 58
  },
  {
    "kind": "bract",
    "src": "/petals/petal-03-soft.png",
    "w": 43,
    "h": 63
  },
  {
    "kind": "bract",
    "src": "/petals/petal-04-soft.png",
    "w": 43,
    "h": 54
  },
  {
    "kind": "bract",
    "src": "/petals/petal-05-soft.png",
    "w": 58,
    "h": 46
  },
  {
    "kind": "bract",
    "src": "/petals/petal-06-soft.png",
    "w": 48,
    "h": 56
  },
  {
    "kind": "bud",
    "src": "/petals/bract-14-soft.png",
    "w": 52,
    "h": 40
  },
  {
    "kind": "bud",
    "src": "/petals/bract-16-soft.png",
    "w": 38,
    "h": 43
  },
  {
    "kind": "leaf",
    "src": "/petals/leaf-05-soft.png",
    "w": 73,
    "h": 67
  }
];
