/** GENERATED by scripts/extract-petals.mjs from the floral wordmark. Do not edit by hand. */
export type SpriteKind = "bract" | "leaf";
export interface PetalSprite { kind: SpriteKind; src: string; w: number; h: number }
export const PETAL_SPRITES: readonly PetalSprite[] = [
  {
    "kind": "bract",
    "src": "/petals/bract-01.png",
    "w": 177,
    "h": 131
  },
  {
    "kind": "bract",
    "src": "/petals/bract-02.png",
    "w": 183,
    "h": 132
  },
  {
    "kind": "bract",
    "src": "/petals/bract-03.png",
    "w": 154,
    "h": 194
  },
  {
    "kind": "bract",
    "src": "/petals/bract-04.png",
    "w": 134,
    "h": 136
  },
  {
    "kind": "bract",
    "src": "/petals/bract-05.png",
    "w": 94,
    "h": 166
  },
  {
    "kind": "bract",
    "src": "/petals/bract-06.png",
    "w": 105,
    "h": 100
  },
  {
    "kind": "bract",
    "src": "/petals/bract-07.png",
    "w": 109,
    "h": 92
  },
  {
    "kind": "bract",
    "src": "/petals/bract-08.png",
    "w": 83,
    "h": 116
  },
  {
    "kind": "bract",
    "src": "/petals/bract-09.png",
    "w": 68,
    "h": 103
  },
  {
    "kind": "bract",
    "src": "/petals/bract-10.png",
    "w": 65,
    "h": 71
  },
  {
    "kind": "bract",
    "src": "/petals/bract-14.png",
    "w": 52,
    "h": 40
  },
  {
    "kind": "bract",
    "src": "/petals/bract-16.png",
    "w": 38,
    "h": 43
  },
  {
    "kind": "leaf",
    "src": "/petals/leaf-01.png",
    "w": 102,
    "h": 79
  },
  {
    "kind": "leaf",
    "src": "/petals/leaf-02.png",
    "w": 109,
    "h": 66
  },
  {
    "kind": "leaf",
    "src": "/petals/leaf-03.png",
    "w": 61,
    "h": 98
  },
  {
    "kind": "leaf",
    "src": "/petals/leaf-05.png",
    "w": 73,
    "h": 67
  },
  {
    "kind": "leaf",
    "src": "/petals/leaf-06.png",
    "w": 59,
    "h": 79
  },
  {
    "kind": "leaf",
    "src": "/petals/leaf-07.png",
    "w": 58,
    "h": 76
  }
];
