/**
 * GENERATED by scripts/import-menu.mjs from kikiontheriver.com/menus on 2026-09-22.
 * KIKI does not publish prices, so none are shown. Re-run the script to refresh.
 */
export interface MenuItem { name: string; description: string }
export interface MenuSection { title: string; note?: string; items: MenuItem[] }
export interface Menu { id: string; title: string; sections: MenuSection[]; chef?: string }

export const MENUS: readonly Menu[] = [
  {
    "id": "dinner",
    "title": "Dinner",
    "sections": [
      {
        "title": "Love at First Bite",
        "note": "To share",
        "items": [
          {
            "name": "Hummus",
            "description": "Tahini, Roasted Garlic, Lemon Juice"
          },
          {
            "name": "Tzatziki",
            "description": "Greek Yogurt, Cucumber, Garlic, Dill, Extra Virgin Olive"
          },
          {
            "name": "Htipiti",
            "description": "Whipped Spicy Feta, Roasted Red Pepper, Chillies"
          },
          {
            "name": "Taramasalata",
            "description": "Greek Caviar Spread, Lemon"
          },
          {
            "name": "KIKI Chips",
            "description": "Crispy Zucchini & Eggplant, Tzatziki"
          },
          {
            "name": "Baked Feta",
            "description": "Greek Feta, Honey, Bomb Tomato, Kalamata Olives"
          },
          {
            "name": "Jumbo Prawns",
            "description": "Simply Grilled Madagascar Tiger Prawns, Metaxa Brandy Infused Lemon Oil, Capers, Greek Oregano, Parsley"
          },
          {
            "name": "Gyro Bites",
            "description": "Mini Pita, Tzatziki, Pickle Onions, Cherry Tomatoes, Micro Cilantro Chicken | Lamb"
          },
          {
            "name": "Greek Meatballs",
            "description": "Beef Meatballs in Spiced Tomato Sauce, Greek Yogurt"
          },
          {
            "name": "Crispy Shrimp",
            "description": "Mediterranean Seasoning, Lemon Aioli"
          },
          {
            "name": "Grilled Octopus",
            "description": "Spanish Octopus, Mediterranean Chimichurri, Capers"
          },
          {
            "name": "Chicken Lemon Soup",
            "description": "Chicken Broth, Veggies, Orzo, Lemon"
          },
          {
            "name": "Greek Salad",
            "description": "Vine Ripe Tomatoes, Green Bell Peppers, Red Onion, Cucumber, Kalamata Olives, Feta, Oregano, Red Wine Vinaigrette"
          },
          {
            "name": "Pear Garden Salad",
            "description": "Arugula, Pear Brulee, Red Onion, Pomegranate Seeds, Goat Cheese, Walnuts."
          },
          {
            "name": "Watermelon Salatasi",
            "description": "Feta Cheese, Cont Tomatoes, Mint Vinaigrette, & Pistachios"
          },
          {
            "name": "KIKI Caesar Salad",
            "description": "Romaine Hearts, Pita Chips, Radish, Parmesan Cheese, Caesar Dressing."
          }
        ]
      },
      {
        "title": "Raw and Chilled",
        "note": "",
        "items": [
          {
            "name": "Citrus Coast Crudo",
            "description": "Lavraki, Orange, Roasted Pepper, Chive Oil, & Citrus Leche De Tigre"
          },
          {
            "name": "Oysters",
            "description": "Chef Selected Oysters Cocktail Sauce, Mignonette 7 ea"
          },
          {
            "name": "King Crab Legs 8 oz / 16 oz",
            "description": "Cocktail Sauce, Garlic Butter, Spicy Mayo"
          },
          {
            "name": "Summer Salmon Tartare",
            "description": "Passion Fruit, Yellow Sweet Aji, Seasonal Grapes"
          },
          {
            "name": "Tuna Tartare",
            "description": "Yellow Fin Tuna, Cucumber, Spellete Pepper, Wasabi Mousse, Strained Labneh"
          }
        ]
      },
      {
        "title": "Large Platters",
        "note": "Seafood tower · serves 2 to 4",
        "items": [
          {
            "name": "Lavraki",
            "description": "Mediterranean Sea Bass,"
          },
          {
            "name": "40 oz Tomahawk",
            "description": "Sea Salt, Greek Extra Virgin Olive Oil, Served w/ House Made Pepper Steak Sauce, Chimichurri & Truffle Mashed Potato MP"
          }
        ]
      },
      {
        "title": "Entrees",
        "note": "",
        "items": [
          {
            "name": "8 oz Wagyu Filet Mignon",
            "description": "Sea Salt"
          },
          {
            "name": "14 oz New York Sirloin",
            "description": "Sea Salt, Greek Extra Virgin Olive Oil"
          },
          {
            "name": "Lamb Chops",
            "description": "Caulifower Puree, Truffle Infused Honey"
          },
          {
            "name": "Fisherman’s Orzo",
            "description": "Octopus, Shrimp, Calamari, Lemon-Butter Seafood Broth"
          },
          {
            "name": "Lobster Pasta",
            "description": "Linguini, Ouzo, Chives, Cont Tomatoes"
          },
          {
            "name": "Salmon Saganaki",
            "description": "Pepper Romesco Couli, Arugula, Fennel, Pomegranate Seeds, Feta Crumble"
          },
          {
            "name": "Mushroom Risotto",
            "description": "Chef Deluxe Mushrooms , Arborio Rice"
          },
          {
            "name": "Mezzi Rigatoni",
            "description": "Rustic Tomato and Creamy Feta Sauce, Basil, Oregano, Rigatoni Pasta"
          },
          {
            "name": "Chicken Kebab",
            "description": "Baby Potatoes, Arugula & Fennel Salad, Tzatziki, Lemon"
          },
          {
            "name": "Au Poivre Sauce",
            "description": "Veal Demi Glaze, Green Peppercorns, Cream"
          },
          {
            "name": "Black Garlic Chicken Sauce",
            "description": "Roasted Chicken Broth infused with Black Garlic"
          },
          {
            "name": "Chimichuri",
            "description": "Fresh Herbs, Espellete Pepper, Shallots"
          }
        ]
      },
      {
        "title": "Sides",
        "note": "",
        "items": [
          {
            "name": "Grilled Asparagus",
            "description": "Lemon, Olive Oil, Herbs"
          },
          {
            "name": "Mashed Potato",
            "description": "Rustic Potato Purée +Infused w/ Black Truffles"
          },
          {
            "name": "Mediterranean Roasted Vegetables",
            "description": "Oven Roasted Peppers, Zucchini, Squash, Onions w/ Aromatic Herbs, Garlic, Grated Tomatoes & Greek Olive Oil"
          },
          {
            "name": "KIKI Fries",
            "description": "Potato Fries, Oregano, Greek Feta"
          },
          {
            "name": "Organic Mushrooms",
            "description": "Sautéed Mixed Mushrooms, Garlic, Herbs"
          },
          {
            "name": "Lemon Roasted Potatoes",
            "description": "Extra Virgin Olive Oil, Garlic, Oregano, Lemon Juice"
          }
        ]
      }
    ],
    "chef": "Executive Chef: Wladimir Arevalo"
  },
  {
    "id": "lunch",
    "title": "Lunch",
    "sections": [
      {
        "title": "Appetizers",
        "note": "",
        "items": [
          {
            "name": "Pikilia Platter",
            "description": "Hummus, Taramosalata, Tzatziki, Htipiti, Grilled Pita"
          },
          {
            "name": "KIKI Chips",
            "description": "Crispy Zucchini and Eggplant, Tzatziki"
          },
          {
            "name": "Baked Feta",
            "description": "Greek Feta, Honey, Bomb Tomato, Orange Zest, Pistachios Kalamata Olives"
          },
          {
            "name": "Greek Meatballs",
            "description": "Beef Meatballs in Spiced Tomato Sauce, Greek Yogurt"
          },
          {
            "name": "Crispy Shrimp",
            "description": "Mediterranean Seasoning, Lemon Garlic Aioli"
          },
          {
            "name": "Grilled Octopus",
            "description": "Spanish Octopus, Mediterranean Chimichurri, Capers"
          }
        ]
      },
      {
        "title": "Salads",
        "note": "",
        "items": [
          {
            "name": "Greek Salad",
            "description": "Vine Ripe Tomatoes, Green Bell Peppers, Red Onion, Cucumber, Kalamata Olives, Feta, Oregano, Red Wine Vinaigrette"
          },
          {
            "name": "Pear Garden Salad",
            "description": "Arugula, Pear Brulee, Red Onion, Pomegranate Seeds, Goat Cheese, Walnuts"
          },
          {
            "name": "Watermelon Salatasi",
            "description": "Feta Cheese, Confit Tomatoes, Mint Vinaigrette, & Pistachios"
          },
          {
            "name": "KIKI Caesar Salad",
            "description": "Romaine Hearts, Radish, Croutons, Shaved Parmesan Cheese, Yogart Caesar Dressing"
          },
          {
            "name": "Chicken Lemon Soup",
            "description": "Chicken Broth, Veggies, Orzo, Lemon"
          }
        ]
      },
      {
        "title": "Raw Bar",
        "note": "",
        "items": [
          {
            "name": "Oysters",
            "description": "Chef Selected Oysters, Cocktail Sauce, Mignonette 7 ea"
          },
          {
            "name": "Tuna Tartare",
            "description": "Yellow Fin Tuna, Cucumber, Spellete Pepper, Wasabi Mousse, Strained Labneh"
          },
          {
            "name": "Citrus Coast Crudo",
            "description": "Lavraki, Orange, Roasted Pepper, Chive Oil & Citrus Leche De Tigre"
          },
          {
            "name": "Summer Salmon Tartare",
            "description": "Passion Fruit, Yellow Sweet Aji, Seasonal Grapes"
          }
        ]
      },
      {
        "title": "Entrées",
        "note": "",
        "items": [
          {
            "name": "Chicken Kebab",
            "description": "Baby Potatoes, Arugula & Fennel Salad, Tzatziki, Lemon"
          },
          {
            "name": "Black Anguschurrasco Steak",
            "description": "Simply Grilled Skirt Steak,Chimichurri, Greek Fries"
          },
          {
            "name": "Lobster Pasta",
            "description": "Linguini, Ouzo, Chives, Confit Tomatoes"
          },
          {
            "name": "Lamb Chops",
            "description": "Cauliflower Puree, Truffle, Infused Honey"
          },
          {
            "name": "Mezzi Rigatoni",
            "description": "Rustic Tomato and Creamy Feta Sauce, Basil, Oregano, Rigatoni Pasta"
          }
        ]
      },
      {
        "title": "Sides",
        "note": "",
        "items": [
          {
            "name": "Grilled Broccolini",
            "description": "Chard Broccolini, Lemon, Olive Oil, Herbs"
          },
          {
            "name": "KIKI Fries",
            "description": "Potato Fries, Oregano, Greek Feta"
          },
          {
            "name": "Lemon Roasted Potatoes",
            "description": "Extra Virgin Olive Oil, Garlic, Oregano, Lemon Juice"
          }
        ]
      }
    ],
    "chef": "Executive Chef: Wladimir Arevalo"
  },
  {
    "id": "cocktails",
    "title": "Cocktails",
    "sections": [
      {
        "title": "Cocktails",
        "note": "",
        "items": [
          {
            "name": "The Pornberry",
            "description": "Grey Goose Infused with Madagascar Vanilla, Fresh Passionfruit & Strawberry, Wild Lily Flower Infusion"
          },
          {
            "name": "Amethyst",
            "description": "Tito’s Handmade Vodka & Fresh Lychee, St. Germaine Elderflower Liqueur, Ube & Violets"
          },
          {
            "name": "Madam Yuzu",
            "description": "Perrier-Jouët ‘Grand Brut’ Champagne, Inniskillin Ice Wine, Japanese Yuzu, Rose Petals, Blue Jasmine"
          },
          {
            "name": "KIKI X.O",
            "description": "Remy Martin X.O Cognac, Macallan 12-Year Scotch, Fresh Lemon & Pomegranate Molasses, Cointreau, Lillet Rosé, Rose Mist"
          },
          {
            "name": "Tierra Santa",
            "description": "Monkey ’47’ Dry Gin, Cucumber, Kiwi, & Green Apple, Luxardo ‘Del Santo’ Liqueur, Manzanilla Sherry, Ceremonial Grade Matcha, Palo Santo Ritual"
          },
          {
            "name": "Athena Nior",
            "description": "Patron Reposado, Kiki Barrel Select, Espresso Cold Brew, Demerara Vanilla Syrup"
          },
          {
            "name": "Jefa’s Margarita 2.0",
            "description": "Casa Dragones Blanco Tequila, Italicus Bergamot Liqueur, Fresh Blackberry, Japanese Yuzu & Jasmine Pearl Tea, Himalayan Pink & Sea Salt, Thai Basil Flame"
          },
          {
            "name": "Casa Mule",
            "description": "Casa Dragones Blanco Tequila, Blood Orange & Lime Juice, Fever Tree Ginger Beer, Rosemary, Oaxacan Molé Essence"
          },
          {
            "name": "Puffer Fish Paloma",
            "description": "Don Julio Blanco Tequila, Jalapeño & Guava Reduction, Mango Liquor, Fresh Lime, Grapefruit Soda, ‘Spicy Lips’"
          },
          {
            "name": "Once Upon A Time",
            "description": "Bacardi ‘8’ & Santa Teresa '1796' Rums, Hawaiian Passionfruit, Orange & Guava Juice, Hibiscus Infused Orgeat, Mint"
          },
          {
            "name": "KIKI Love Potion",
            "description": "Ketel One Vodka, St. Germain Elderflower Liqueur, Juliette Heirloom Peach, Butterfly Pea-Flower Tea"
          },
          {
            "name": "Mango Oolong Mezcalita",
            "description": "Mezcal VIDA Espadin & Código Tequila Blanco, JOJO Wuyi Mountain Oolong, Fresh Mango, Cold-Pressed Ginger Juice, Hawaiian Lava Salt"
          }
        ]
      },
      {
        "title": "Frozen",
        "note": "",
        "items": [
          {
            "name": "Coco Melon Margarita",
            "description": "Patron Blanco & Reposado, Cointreau Orange Liqueur, Cold-Pressed Watermelon Juice, Organic Coconut Milk, Himalayan Pink Salt"
          },
          {
            "name": "Playa Papaya Mojito",
            "description": "Santa Teresa 1796 Rum, Fresh Mint & Lime Juice, Papaya Pureé"
          },
          {
            "name": "De Piña",
            "description": "Bacardi ‘8’, Martell 'Blue Swift', Organic Coconut Cream, Fresh Pineapple Juice"
          },
          {
            "name": "KIKI Froze",
            "description": "Grey Goose, Hibiscus & Strawberry, Rosé Wine, Red Bull 'Watermelon' Edition"
          }
        ]
      },
      {
        "title": "KIKI Shots",
        "note": "",
        "items": [
          {
            "name": "KIKI Love Shots",
            "description": "Casamigos Blanco Tequila, Strawberry & Lime Juice, JF Hayden Lychee Liqueur"
          },
          {
            "name": "Passion Berry Shots",
            "description": "Código 1530 Blanco Tequila, Passionfruit, Strawberry"
          },
          {
            "name": "Cafecito Shots",
            "description": "Absolut Vanilla Vodka, Crème de Moka, Licor 43, Panther Cold Brew Coffee Minimum of 2"
          }
        ]
      },
      {
        "title": "Mocktails",
        "note": "",
        "items": [
          {
            "name": "Miss Jinna",
            "description": "Lychee, Yuzu, Strawberry, Rose, Lavender Essence"
          },
          {
            "name": "Peaches",
            "description": "Winter White Peach, Fresh Lemon Juice, Soda Water, Rosemary"
          }
        ]
      }
    ],
    "chef": ""
  },
  {
    "id": "brunch",
    "title": "Brunch",
    "sections": [
      {
        "title": "À la Carte",
        "note": "Every Saturday & Sunday · 12:30 – 4:30 PM",
        "items": [
          {
            "name": "KIKI Lobster Toast",
            "description": "\"ick Cut Toasted Brioche, Avocado Poached Lobster, Tomato Hollandaise, Chives"
          },
          {
            "name": "Shakshuka Classic",
            "description": "Three Organic Eggs Baked In A House-Made Mild Tomato, Pepper Sauce"
          },
          {
            "name": "Steak & Eggs",
            "description": "Marinated Skirt Steak, Three Eggs Any Style, Fries"
          },
          {
            "name": "Mini Chicken Gyros",
            "description": "Warm Pita, Grilled Chicken, Tzatziki, Tomato, Pickled Red Onion, Fresh Herbs"
          },
          {
            "name": "Beets Me",
            "description": "Roasted Beet Hummus, Avocado Poached egg, Toasted Sourdough, Feta Cheese"
          },
          {
            "name": "Aegean French Toast",
            "description": "Brioche, Citrus Zest, Fresh Berries, Greek Yogurt, Pomegranate Syrup"
          }
        ]
      },
      {
        "title": "Raw Bar",
        "note": "",
        "items": [
          {
            "name": "Oysters",
            "description": "Chef Selected Oysters Cocktail Sauce, Mignonette 7 ea"
          },
          {
            "name": "Citrus Coast Crudo",
            "description": "Lavraki, Orange, Roasted Pepper, Chive Oil, & Citrus Leche De Tigre"
          },
          {
            "name": "Summer Salmon Tartare",
            "description": "Passion Fruit, Yellow Sweet Aji, Seasonal Grapes"
          },
          {
            "name": "Tuna Tartare",
            "description": "Yellow Fin Tuna, Cucumber Spellete Pepper, Wasabi Mousse, Strained Labneh"
          }
        ]
      },
      {
        "title": "KIKI's Classics",
        "note": "",
        "items": [
          {
            "name": "Lavraki",
            "description": "Mediterranean Sea Bass,"
          },
          {
            "name": "Lamb Chops",
            "description": "Cauliower Puree, True Infused Honey"
          },
          {
            "name": "Lobster Pasta",
            "description": "Linguini, Ouzo, Chives, Cont Tomatoes"
          }
        ]
      },
      {
        "title": "Appetizers",
        "note": "",
        "items": [
          {
            "name": "KIKI Chips",
            "description": "Crispy Zucchini and Eggplant, Tzatziki"
          },
          {
            "name": "Pikilia Platter",
            "description": "Hummus, Taramosalata, Tzatziki, Htipiti, Grilled Pita"
          },
          {
            "name": "Baked Feta",
            "description": "Greek Feta, Honey, Bomb Tomato,Orange Zest, Pistachios Kalamata Olives"
          }
        ]
      },
      {
        "title": "Salad",
        "note": "",
        "items": [
          {
            "name": "Watermelon Salatasi",
            "description": "Feta Cheese, Cont Tomatoes, Mint Vinaigrette,& Pistachios"
          },
          {
            "name": "Greek Salad",
            "description": "Vine Ripe Tomatoes, Green Bell Peppers, Red Onion, Cucumber, Kalamata Olives, Fets, Oregano,Red Wine Vinaigrette"
          },
          {
            "name": "KIKI Caesar Salad",
            "description": "Romaine Hearts, Radish, Croutons, Shaved Parmesan Cheese, Yogart Caesar Dressing"
          },
          {
            "name": "Pear Garden Salad",
            "description": "Arugula, Pear Brulee, Red Onion, Pomegranate Seeds, Goat Cheese, Walnuts"
          }
        ]
      },
      {
        "title": "Sides",
        "note": "",
        "items": [
          {
            "name": "Mediterranean Roasted Vegetables",
            "description": "Oven Roasted Peppers, Zucchini, Squash, Onions w/ Aromatic Herbs, Eggplant, Garlic, Grated Tomatoes Lemon Zest, & Greek Olive Oil"
          },
          {
            "name": "KIKI Fries",
            "description": "Potato Fries, Oregano, Greek Feta +Truffle Oil"
          },
          {
            "name": "Lemon Roasted Potatoes",
            "description": "Extra Virgin Olive Oil, Garlic, Oregano, Lemon Juice"
          }
        ]
      }
    ],
    "chef": "Executive Chef: Wladimir Arevalo"
  },
  {
    "id": "happy-hour",
    "title": "Happy Hour",
    "sections": [
      {
        "title": "Happy Hour",
        "note": "Monday to Friday · 5 – 7 PM · at the bar only",
        "items": []
      },
      {
        "title": "$10 Drinks",
        "note": "",
        "items": [
          {
            "name": "Lychee Martini",
            "description": "Absolut Vodka, Lychee Puree, Agave"
          },
          {
            "name": "Moscow Mule",
            "description": "Absolut Vodka, Lime, Agave, Ginger Beer"
          },
          {
            "name": "Aperol Spritz",
            "description": "Aperol, Prosecco, Soda Water, Fresh Orange"
          }
        ]
      },
      {
        "title": "Wines",
        "note": "",
        "items": [
          {
            "name": "Red",
            "description": ""
          },
          {
            "name": "White",
            "description": ""
          },
          {
            "name": "Rose",
            "description": ""
          },
          {
            "name": "Sparkling",
            "description": ""
          }
        ]
      },
      {
        "title": "$20 Drinks",
        "note": "",
        "items": [
          {
            "name": "The Pornberry",
            "description": "Grey Goose Infused with Madagascar Vanilla, Fresh Passionfruit & Strawberry, Wild Lily Flower Infusion"
          },
          {
            "name": "Jefa’s Margarita 2.0",
            "description": "Casa Dragones Blanco Tequila, Italicus Bergamot Liqueur, Fresh Blackberry, Japanese Yuzu & Jasmine Pearl Tea, Himalayan Pink & Sea Salt, Thai Basil Flame"
          },
          {
            "name": "Casa Mule",
            "description": "Casa Dragones Blanco Tequila, Blood Orange & Lime Juice, Fever Tree Ginger Beer, Rosemary, Oaxacan Molé Essence"
          },
          {
            "name": "Once Upon A Time",
            "description": "Bacardi ‘8’ & Santa Teresa '1796' Rums, Hawaiian Passionfruit, Orange & Guava Juice, Hibiscus Infused Orgeat, Mint"
          },
          {
            "name": "Espresso Martini",
            "description": "Grey Goose Vodka, Espresso Cold Brew, Crême de Moka"
          }
        ]
      }
    ],
    "chef": ""
  },
  {
    "id": "dessert",
    "title": "Dessert",
    "sections": [
      {
        "title": "Desserts",
        "note": "",
        "items": [
          {
            "name": "Pistachio Dream",
            "description": "Labneh Mousse, Pistachio Praline, Pomegranate, Lemon Zest"
          },
          {
            "name": "Baklava Bites",
            "description": "Pistachio Baklava, served with assorted berries *Gelato à la Mode"
          },
          {
            "name": "Hazelut Crunch Cake",
            "description": "Chocolate, with a Hazelnut Crunch, and berry coulis"
          },
          {
            "name": "Portokalopita",
            "description": "Traditional Greek filo orange cake, with honey syrup and gelato"
          },
          {
            "name": "KIKI's Naughty Kiss",
            "description": "Key Lime Panna Cotta, with a Duo of Passion Fruit Sauces"
          }
        ]
      }
    ],
    "chef": ""
  }
];

export const MENU_DISCLAIMER =
  "A service charge of 22% is applied to all checks. Consuming raw or undercooked meats, poultry, seafood, shellfish or eggs may increase your risk of food-borne illness.";
