/**
 * Cuts individual bougainvillea bracts and leaves out of the floral wordmark
 * PNG so the falling petals are the brand's own flowers.
 *
 *   node scripts/extract-petals.mjs
 *
 * Writes public/petals/*.png and lib/petal-sprites.ts.
 */
import sharp from "sharp";
import { mkdir, writeFile, rm } from "node:fs/promises";

const SRC = "assets/source/14-kiki-wordmark-flowers-transparent.png";
const OUT = "public/petals";
await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const { data, info } = await sharp(SRC).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
const { width: W, height: H } = info;
const N = W * H;
const px = (i) => [data[i * 4], data[i * 4 + 1], data[i * 4 + 2], data[i * 4 + 3]];

/* Pixel classes. */
const CLS = new Uint8Array(N); // 0 none, 1 bract (red/magenta), 2 leaf (green), 3 white
for (let i = 0; i < N; i++) {
  const [r, g, b, a] = px(i);
  if (a < 120) continue;
  if (r > 225 && g > 225 && b > 225) CLS[i] = 3;
  else if (r > 120 && r > g * 1.7 && r > b * 1.15) CLS[i] = 1;
  else if (g > 70 && g > r * 1.15 && g > b * 1.15) CLS[i] = 2;
}

/* Connected components (8-way) of a class. */
function components(cls) {
  const seen = new Uint8Array(N);
  const out = [];
  const stack = new Int32Array(N);
  for (let s = 0; s < N; s++) {
    if (CLS[s] !== cls || seen[s]) continue;
    let sp = 0;
    stack[sp++] = s;
    seen[s] = 1;
    const pixels = [];
    let x0 = W, x1 = 0, y0 = H, y1 = 0;
    while (sp) {
      const i = stack[--sp];
      pixels.push(i);
      const x = i % W, y = (i / W) | 0;
      if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y;
      for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) {
        const nx = x + dx, ny = y + dy;
        if (nx < 0 || ny < 0 || nx >= W || ny >= H) continue;
        const j = ny * W + nx;
        if (!seen[j] && CLS[j] === cls) { seen[j] = 1; stack[sp++] = j; }
      }
    }
    out.push({ pixels, x0, x1, y0, y1, area: pixels.length });
  }
  return out;
}

/* Big white components are the letters and subtitle; small ones are flower centres. */
const whiteBig = new Uint8Array(N);
for (const c of components(3)) if (c.area > 1500) for (const i of c.pixels) whiteBig[i] = 1;

async function writeSprite(comp, name, pad = 3) {
  const x0 = Math.max(0, comp.x0 - pad), y0 = Math.max(0, comp.y0 - pad);
  const x1 = Math.min(W - 1, comp.x1 + pad), y1 = Math.min(H - 1, comp.y1 + pad);
  const w = x1 - x0 + 1, h = y1 - y0 + 1;
  // Membership: the component dilated by 2px, plus any small-white (flower centre) pixel inside the box.
  const member = new Uint8Array(w * h);
  for (const i of comp.pixels) {
    const x = i % W, y = (i / W) | 0;
    for (let dy = -2; dy <= 2; dy++) for (let dx = -2; dx <= 2; dx++) {
      const nx = x + dx - x0, ny = y + dy - y0;
      if (nx >= 0 && ny >= 0 && nx < w && ny < h) member[ny * w + nx] = 1;
    }
  }
  const buf = Buffer.alloc(w * h * 4);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const si = (y + y0) * W + (x + x0);
    const [r, g, b, a] = px(si);
    const isSmallWhite = CLS[si] === 3 && !whiteBig[si];
    const keep = (member[y * w + x] && !whiteBig[si]) || isSmallWhite;
    const o = (y * w + x) * 4;
    buf[o] = r; buf[o + 1] = g; buf[o + 2] = b; buf[o + 3] = keep ? a : 0;
  }
  // Feather the alpha slightly so the cut edge is anti-aliased.
  const rgb = await sharp(buf, { raw: { width: w, height: h, channels: 4 } }).removeAlpha().raw().toBuffer();
  const alpha = await sharp(buf, { raw: { width: w, height: h, channels: 4 } }).extractChannel(3).blur(0.7).raw().toBuffer();
  await sharp(rgb, { raw: { width: w, height: h, channels: 3 } })
    .joinChannel(alpha, { raw: { width: w, height: h, channels: 1 } })
    .png({ compressionLevel: 9 })
    .toFile(`${OUT}/${name}.png`);
  return { src: `/petals/${name}.png`, w, h };
}

/* Cuts that were sliced by a letter edge and read as fragments. Indices are 1-based, by area rank. */
const SKIP_BRACTS = new Set([11, 12, 13, 15]);
const SKIP_LEAVES = new Set([4, 8]);

const bracts = components(1)
  .filter((c) => c.area >= 500 && c.area <= 14000 && (c.x1 - c.x0) < 260 && (c.y1 - c.y0) < 260)
  .sort((a, b) => b.area - a.area)
  .slice(0, 16);
const leaves = components(2)
  .filter((c) => c.area >= 350 && c.area <= 6000)
  .sort((a, b) => b.area - a.area)
  .slice(0, 8);

const sprites = [];
let n = 0;
for (const c of bracts) {
  n++;
  if (SKIP_BRACTS.has(n)) continue;
  sprites.push({ kind: "bract", ...(await writeSprite(c, `bract-${String(n).padStart(2, "0")}`)) });
}
n = 0;
for (const c of leaves) {
  n++;
  if (SKIP_LEAVES.has(n)) continue;
  sprites.push({ kind: "leaf", ...(await writeSprite(c, `leaf-${String(n).padStart(2, "0")}`)) });
}

const ts = `/** GENERATED by scripts/extract-petals.mjs from the floral wordmark. Do not edit by hand. */
export type SpriteKind = "bract" | "leaf";
export interface PetalSprite { kind: SpriteKind; src: string; w: number; h: number }
export const PETAL_SPRITES: readonly PetalSprite[] = ${JSON.stringify(sprites, null, 2)};
`;
await writeFile("lib/petal-sprites.ts", ts);
console.log(`wrote ${sprites.length} sprites (${bracts.length} bracts, ${leaves.length} leaves)`);
console.table(sprites.map((s) => ({ kind: s.kind, src: s.src, w: s.w, h: s.h })));
