/**
 * Parses KIKI's live menus page (Elementor nested tabs + price lists) into
 * data/menu.ts. Prices are not published on the live site, so none are invented.
 *
 *   node scripts/import-menu.mjs [path/to/menus.html]   (defaults to fetching the live page)
 */
import { writeFile, readFile } from "node:fs/promises";

const src = process.argv[2];
const html = src
  ? await readFile(src, "utf8")
  : await (await fetch("https://www.kikiontheriver.com/menus/", { headers: { "user-agent": "Mozilla/5.0" } })).text();

const clean = (s) =>
  s.replace(/<[^>]+>/g, " ").replace(/&amp;|&#038;/g, "&").replace(/&#8217;|&#x27;|&#39;|&rsquo;/g, "’").replace(/&#8211;|&#8212;|&ndash;|&mdash;/g, "–")
    .replace(/&nbsp;/g, " ").replace(/&quot;/g, '"').replace(/\s+/g, " ").trim();
const title = (s) => clean(s).toLowerCase().replace(/(^|[\s(/–-])([a-z])/g, (m, p, c) => p + c.toUpperCase()).replace(/\bKiki\b/g, "KIKI").replace(/\bX\.o\b/gi, "X.O").replace(/(\d+)oz/gi, "$1 oz").replace(/\bOf\b/g, "of").replace(/\bAnd\b/g, "and").replace(/\bThe\b(?!$)/g, "the").replace(/^the/, "The");

/* Tab titles, in order (the top-level tabs widget). */
const tabsBlock = html.slice(html.indexOf('class="e-n-tabs-heading"'));
const tabTitles = [...tabsBlock.matchAll(/class="e-n-tab-title-text"[^>]*>([\s\S]*?)<\/span>/g)].map((m) => clean(m[1]));
/* Content panes, each pane's HTML. */
const paneRe = /<div[^>]*class="[^"]*e-n-tabs-content[^"]*"[^>]*>([\s\S]*)$/;
const content = paneRe.exec(html)?.[1] ?? html;
/* Split into panes on the "e-con e-n-tab-content"-style wrappers by id pattern e-n-tab-content-XXXX-N */
/* Pane ids may carry an extra anchor word (id="e-n-tab-content-123 lunch"). Keep the first tabs widget only (7 menus). */
const paneIds = [...content.matchAll(/id="(e-n-tab-content-[0-9]+)[^"]*"/g)].map((m) => m[1]).slice(0, 7);
const panes = paneIds.map((id, i) => {
  const a = content.indexOf(`id="${id}`);
  const b = i + 1 < paneIds.length ? content.indexOf(`id="${paneIds[i + 1]}`) : content.length;
  return content.slice(a, b);
});

/* Walk a pane in document order: headings (h2-h5) and price-list items. */
const tokenRe = /<h([2-5])[^>]*>([\s\S]*?)<\/h\1>|<div class="uael-price-list-item">([\s\S]*?)<span class="uael-price-wrapper/g;
const menus = panes.map((pane, i) => {
  if (/^bottle service$/i.test(tabTitles[i] || "")) return null; // a pricing table, not a dish list
  const sections = [];
  let cur = null;
  for (const m of pane.matchAll(tokenRe)) {
    if (m[1]) {
      const t = clean(m[2]);
      if (!t || t.length > 60) continue;
      if (/OUR MENU|Enjoy one of/i.test(t)) continue;
      if (cur && cur.items.length === 0 && !cur.note) { cur.note = t; continue; } // a subtitle under a heading
      cur = { title: title(t), note: "", items: [] };
      sections.push(cur);
    } else {
      const name = clean(/uael-price-list-title[^>]*>\s*<span>([\s\S]*?)<\/span>/.exec(m[3])?.[1] ?? "");
      const desc = clean(/uael-price-list-description">([\s\S]*?)<\/p>/.exec(m[3])?.[1] ?? "");
      if (!name) continue;
      if (!cur) { cur = { title: "", note: "", items: [] }; sections.push(cur); }
      cur.items.push({ name: title(name).replace(/[:：]\s*$/, ""), description: desc });
    }
  }
  const footer = clean(/(Executive Chef[^<]*)/.exec(pane)?.[1] ?? "");
  return { id: (tabTitles[i] || `menu-${i + 1}`).toLowerCase().replace(/[^a-z0-9]+/g, "-"), title: title(tabTitles[i] || `Menu ${i + 1}`), sections: sections.filter((s) => s.items.length || s.note), chef: footer };
});

/* Small hand corrections where the live page's headings read as dishes or hours. */
const FIX = {
  "Love At First Bite": { title: "Love at First Bite", note: "To share" },
  "Seafood Tower": { title: "Large Platters", note: "Seafood tower · serves 2 to 4" },
  "Every Saturday & Sunday 12:30 Pm - 4:30 Pm": { title: "À la Carte", note: "Every Saturday & Sunday · 12:30 – 4:30 PM" },
  "At the Bar Only": { title: "Happy Hour", note: "Monday to Friday · 5 – 7 PM · at the bar only" },
  "Selection of Wines": { title: "Wines", note: "" },
};
for (const m of menus.filter(Boolean)) for (const s of m.sections) { const f = FIX[s.title]; if (f) Object.assign(s, f); if (s.note && /^\[?(pikilia platter|spirits)/i.test(s.note)) s.note = ""; }

const out = `/**
 * GENERATED by scripts/import-menu.mjs from kikiontheriver.com/menus on ${new Date().toISOString().slice(0, 10)}.
 * KIKI does not publish prices, so none are shown. Re-run the script to refresh.
 */
export interface MenuItem { name: string; description: string }
export interface MenuSection { title: string; note?: string; items: MenuItem[] }
export interface Menu { id: string; title: string; sections: MenuSection[]; chef?: string }

export const MENUS: readonly Menu[] = ${JSON.stringify(menus.filter((m) => m && m.sections.length), null, 2)};

export const MENU_DISCLAIMER =
  "A service charge of 22% is applied to all checks. Consuming raw or undercooked meats, poultry, seafood, shellfish or eggs may increase your risk of food-borne illness.";
`;
await writeFile("data/menu.ts", out);
console.log(menus.filter(Boolean).map((m) => `${m.title}: ${m.sections.length} sections, ${m.sections.reduce((n, s) => n + s.items.length, 0)} items`).join("\n"));
